# Site
name: "Pratyush"
title: "pratyush"
description: "Performance Engineering Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'G-MV0PS2D023'
disqus: 'pratyush1806'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  pratyush:
    name: pratyush
    display_name: Pratyush Majumdar
    avatar: 'assets/images/avatar.webp'
    gravatar: 4687f9747f79851480efcea1194cfa19    
    email: pratyush.majumdar@gmail.com
    web: https://pratyush1806.github.io
    twitter: https://twitter.com/_pratyush
    description: "Technology Enthusiast, Performance Specialist and Cloud Architect"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [LICENSE.txt, README.md, Gemfile, Gemfile.lock]
